### ISSUE TITLE
index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by iefhanz** [tonyke-bot/ore-miner#14]
so i test the code with 0 sol on wallet AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL
revealing error like this

```
2024-04-14T09:54:50Z INFO  ore_miner::bundle_mine_gpu] 25 keys loaded
[2024-04-14T09:54:50Z INFO  ore_miner::bundle_mine_gpu] splitted signers into batches
[2024-04-14T09:54:50Z INFO  ore_miner::bundle_mine_gpu] subscribed to jito tip stream
[2024-04-14T09:54:50Z ERROR ore_miner::bundle_mine_gpu] fail to fetch proof accounts: account AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL not registered
[2024-04-14T09:54:51Z ERROR ore_miner::bundle_mine_gpu] fail to fetch proof accounts: account AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL not registered
[2024-04-14T09:54:51Z ERROR ore_miner::bundle_mine_gpu] fail to fetch proof accounts: account AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL not registered
[2024-04-14T09:54:52Z ERROR ore_miner::bundle_mine_gpu] fail to fetch proof accounts: account AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL not registered
[2024-04-14T09:54:53Z ERROR ore_miner::bundle_mine_gpu] fail to fetch proof accounts: account AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL not registered
[2024-04-14T09:54:53Z ERROR ore_miner::bundle_mine_gpu] fail to fetch proof accounts: account AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL not registered
[2024-04-14T09:54:54Z ERROR ore_miner::bundle_mine_gpu] fail to fetch proof accounts: account AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL not registered
[2024-04-14T09:54:54Z ERROR ore_miner::bundle_mine_gpu] fail to fetch proof accounts: account AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL not registered
[2024-04-14T09:54:55Z ERROR ore_miner::bundle_mine_gpu] fail to fetch proof accounts: account AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL not registered
^C[2024-04-14T09:54:56Z ERROR ore_miner::bundle_mine_gpu] fail to fetch proof accounts: account AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL not registered
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ore-program-1.2.0/src/state/proof.rs:39:1:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
then i deposited some sol on AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL, run the code again, then this error code appears

```
Finished `release` profile [optimized + debuginfo] target(s) in 0.30s
     Running `target/release/ore-miner --rpc myrpc.com' --priority-fee 500000 bundle-mine-gpu --key-folder /root/ore-miner/mode --max-adaptive-tip 400000`
[2024-04-14T10:00:29Z INFO  ore_miner::bundle_mine_gpu] 25 keys loaded
[2024-04-14T10:00:29Z INFO  ore_miner::bundle_mine_gpu] splitted signers into batches
[2024-04-14T10:00:29Z INFO  ore_miner::bundle_mine_gpu] subscribed to jito tip stream
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ore-program-1.2.0/src/state/proof.rs:39:1:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

how to fix it ?

**Comment by shouc** [comment]
Have you registered these wallets?

**Comment by iefhanz** [comment]
> Have you registered these wallets?

so i tried to fund the wallet from private key id for registering all the wallet.
funded with 0.5$ for testing to the pubkey i retrieve from error message.(AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL)

after checking, the pubkey was different from the wallet that i grab from cointools, i don't have idea where AHTBDZmWrNDKZ4H7fVPYVnkTFmEo996fQT4HEVm3WEAL come from

**Comment by iefhanz** [comment]
im trying to fund my wallet 25
but still get an error
```
[2024-04-16T11:30:49Z INFO  ore_miner::register] registering 23 accounts
[2024-04-16T11:30:49Z ERROR ore_miner::register] fail to simulate transaction: Error processing Instruction 0: custom program error: 0x1
```
which means the pubkey in the error, not my pubkey
how to find out all pubkeys that i retrieve from the error?
